### PR TITLE
Added Restrict YouTube & Easy Script to remove everything.

### PR DESCRIPTION
**Pull request by AustinSaintAubin**
Restrict YouTube content on your network
https://support.google.com/a/answer/6214622?vid=1-635785611429575043-491764474

### CODE REVIEW

**Comment by blowrancebenton** [comment]
Nice!  I'll test before merging.  Have you tested that these do work and successfully restrict YouTube content to Google Apps domain approved videos?  If so, what client OS and DNS Server OS did you test between?

**Comment by AustinSaintAubin** [comment]
Tested on Server 2012 R2 and found the scripts to work well. The "Create Delete-GoogleSafeSearch-DNSEntries.ps1" script might need a little code cleanup.
But both worked well.

Tested youtube after clearing DNS chache on Mac OS 10.10.5 with Chrome Version 45.0.2454.99 (64-bit), also tested incognito mode and seems to work well.

You might wait a day or two before merging, just in case I find an issue.

---

Infrastructure is k-12 school with 300+ devices.
Youtube content filter seems to work right off the bat (24 hours later) for student devices after DNS server update.
The nice thing is that if you have Google Apps you can set YouTube video approvers. See:
https://support.google.com/a/answer/6214622?vid=1-635785611429575043-491764474
https://support.google.com/a/answer/6208224?vid=1-635785611429575043-491764474

**Comment by flamingpeep2** [comment]
Can the owner or someone please help me. I do not know what exactly to change $AD_DNS_Server = "DC1.DOMAIN.LOCAL" to. I tried dc01.local. I tried jacob.local since that is the name of the computer. I also tried 208.67.222.222 I do not know what to put. Can someone please help.

**Comment by flamingpeep2** [comment]
jacob is my computer's dns name.

**Comment by flamingpeep2** [comment]
I tried 192.168.1.1 and a long string of error creating the dns zone for www.google.com came up. Then it says errors occurred during processing, some records could not be created/updated. Please help me owner.

**Comment by flamingpeep2** [comment]
I do not know what my AD DNS Servers are and I can't find it anywhere please help.

**Comment by blowrancebenton** [comment]
This script requires a Windows DNS server to provide DNS services for your network.  In an Active Directory environment this is typically your servers running the Active Directory Domain Controller role.
Typically $AD_DNS_Server would be set to your Active Directory Domain Controller that is running the DNS service and holds the FSMO roles.

If your Active Directory domain name is "contoso.private" and you have domain controllers named "DC1", "DC2" and "DC3".  These all should have the DNS service feature running on them and DC1 is likely the first domain controller implemented therefore holding the FSMO roles.  I would then set $AD_DNS_Server to "dc1.contoso.private".

All of the client computers in the domain should use DC1, DC2 and/or DC3 as their DNS server(s).  DC1, DC2, and DC3 then will then use external DNS servers as forwarders (what ever upstream DNS servers you wish, such as Google's 8.8.8.8, etc).

This script is meant for a network that is running Active Directory and the Active Directory Domain Controller(s) provide DNS to it's clients,  You can certainly setup Windows DNS Server without Active Directory but overall configuration of the DNS Server feature is beyond the scope of this script.  There a several videos and resources out there to show you how to install and configure a basic DNS Server using Windows Server 2012 and 2016.

DNS Concepts:  https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/reviewing-dns-concepts.

**Comment by flamingpeep2** [comment]
Thanks for writing. I'm not a programmer what does contoso mean?

**Comment by flamingpeep2** [comment]
My dns name is jacob. Would I use dc1.jacob? Thank you so much for responding.

**Comment by flamingpeep2** [comment]
dc1.jacob did not work. Can this work using just windows 8.1?

**Comment by blowrancebenton** [comment]
This is meant for an enterprise/business network.

**Comment by flamingpeep2** [comment]
Thanks for trying. Do you know if there is any good option for someone trying to force google safesearch to a home network to help protect children. I use opendns, but blocking google seems impossible since it is used so much.

**Comment by AustinSaintAubin** [comment]
@flamingpeep2 Have a look at:
- https://pi-hole.net/
- https://www.reddit.com/r/pihole/comments/82h77r/google_safesearch/
- https://discourse.pi-hole.net/t/add-a-way-to-force-google-safesearch-through-the-web-interface/2296

**Pull request closed without merging**
